name: Pull Request - Merge

on:
  pull_request:
    types:
      - closed

jobs:
  extract_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Pull Request - Merge
        if: github.event.pull_request.merged
        run: |
          echo ${{ toJSON(github.event.pull_request.head.ref) }}
          echo ${{ github.ref }}
          git log -1 --pretty=format:%s
