name: Pull Request - Merge

on:
  pull_request:
    types:
      - closed

jobs:
  extract_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Pull Request - Merge
        if: github.event.pull_request.merged
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          JIRA_ISSUE_KEY=$(echo "$BRANCH_NAME" | grep -oP '(?<=\/)[A-Z]+-[0-9]+')
          MERGE_COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          echo "$BRANCH_NAME"
          echo "$JIRA_ISSUE_KEY"
          echo "$MERGE_COMMIT_SHA"
          if [ ! -z "$JIRA_ISSUE_KEY" ]; then
            git checkout "$MERGE_COMMIT_SHA"
            git log --format=%B -n 1 | sed "s/\$/ $JIRA_ISSUE_KEY/" | git commit --amend --file=-
            git push -f
          fi

