name: Pull Request - Merge

on:
  pull_request:
    types:
      - closed

jobs:
  extract_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: master
        
      - name: Pull Request - Merge
        if: github.event.pull_request.merged
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          JIRA_ISSUE_KEY=$(echo "$BRANCH_NAME" | grep -oP '(?<=\/)[A-Z]+-[0-9]+')
          if [ -n "$JIRA_ISSUE_KEY" ]; then
            echo "Good"
            git log --format=%B -n 1 | sed "s/\$/ $JIRA_ISSUE_KEY/" | git commit --amend --file=-
            git push -f
          fi

