name: Pull Request - Merge

on:
  pull_request:
    types:
      - closed

jobs:
  extract_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: master
        
      - name: Pull Request - Merge
        if: github.event.pull_request.merged
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          JIRA_ISSUE_KEY="3"
          if [ -n "$JIRA_ISSUE_KEY" ]; then
            echo "Good"
          fi

